{% set version = "4.4.1.p5" %}
{% set name = "singular" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: singular-4.4.1p5.tar.gz
  url: https://github.com/sagemath/sage-package/releases/download/tars/singular-4.4.1p5.tar.gz
  sha256: bce5a40bd10b6e9fe991de97e6284f62cdb566c8aef4b2836b4d1307eb7d9edf
  patches:
    - ncursesw.patch
    - offsetof.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('singular', max_pin='x.x.x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - libtool
    - automake
    - autoconf
    - pkg-config
    - make
    - sed
  host:
    - gmp
    - mpfr
    - ntl
    - libflint {{ libflint }}
    - cddlib
    - readline
    - ncurses
  run:
    - gmp
    - mpfr
    - ntl
    - cddlib
    - readline
    - ncurses

test:
  commands:
    - test -f ${PREFIX}/include/singular/Singular/libsingular.h
    - test -f ${PREFIX}/lib/libSingular.a
    - test -f ${PREFIX}/share/info/singular.info
    - test -f ${PREFIX}/lib/libSingular.dylib     # [osx]
    - test -f ${PREFIX}/lib/libSingular.so        # [linux]

about:
  home: https://www.singular.uni-kl.de/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: |
    Singular is a computer algebra system for polynomial computations, with special emphasis
    on commutative and non-commutative algebra, algebraic geometry, and singularity theory
  dev_url: https://github.com/Singular/Sources

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
