{% set version = "4.2.1" %}
{% set patchlevel = "p3" %}
{% set name = "singular" %}

package:
  name: {{ name }}
  version: {{ version }}.{{ patchlevel }}

source:
  fn: {{ name }}-{{ version }}{{ patchlevel }}.tar.gz
  url: https://www.singular.uni-kl.de/ftp/pub/Math/Singular/SOURCES/{{ version.replace('.', '-') }}/singular-{{ version }}{{ patchlevel }}.tar.gz
  sha256: 14d073b252d6b4f3fce02cebed612d6a09e0eba2bd58384d19b53528c628d71b

build:
  number: 2
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('singular', max_pin='x.x.x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('cxx') }}
    - libtool
    - automake
    - pkg-config
    - make
    - sed
  host:
    - gmp
    - mpfr
    - ntl
    - libflint
    - cddlib
  run:
    - gmp
    - mpfr
    - ntl
    - libflint
    - cddlib

test:
  commands:
    - test -f ${PREFIX}/include/singular/Singular/libsingular.h
    - test -f ${PREFIX}/lib/libSingular.a
    - test -f ${PREFIX}/lib/libSingular.dylib     # [osx]
    - test -f ${PREFIX}/lib/libSingular.so        # [linux]

about:
  home: https://www.singular.uni-kl.de/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: | 
    Singular is a computer algebra system for polynomial computations, with special emphasis
    on commutative and non-commutative algebra, algebraic geometry, and singularity theory
  dev_url: https://github.com/Singular/Sources

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
