{% set version = "4.4.1" %}
{% set name = "singular" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://www.singular.uni-kl.de/ftp/pub/Math/Singular/SOURCES/{{ version.replace('.', '-') }}/singular-{{ version }}.tar.gz
  sha256: 6a4fbaaed05b89c35bff3b1c5e124344a088097f81affe129c9ae619b282b49b
  patches:
    - ncursesw.patch
    - offsetof.patch

build:
  number: 1
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('singular', max_pin='x.x.x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - libtool
    - automake
    - autoconf
    - pkg-config
    - make
    - sed
  host:
    - gmp
    - mpfr
    - ntl
    - libflint {{ libflint }}
    - cddlib
    - readline
    - ncurses
  run:
    - gmp
    - mpfr
    - ntl
    - cddlib
    - readline
    - ncurses

test:
  commands:
    - test -f ${PREFIX}/include/singular/Singular/libsingular.h
    - test -f ${PREFIX}/lib/libSingular.a
    - test -f ${PREFIX}/lib/libSingular.dylib     # [osx]
    - test -f ${PREFIX}/lib/libSingular.so        # [linux]

about:
  home: https://www.singular.uni-kl.de/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: |
    Singular is a computer algebra system for polynomial computations, with special emphasis
    on commutative and non-commutative algebra, algebraic geometry, and singularity theory
  dev_url: https://github.com/Singular/Sources

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
