{% set version = "4.1.1" %}
{% set patchlevel = "p2" %}
{% set name = "singular" %}

package:
  name: {{ name }}
  version: {{ version }}.{{ patchlevel }}

source:
  fn: {{ name }}-{{ version }}{{ patchlevel }}.tar.gz
  url: http://www.mathematik.uni-kl.de/ftp/pub/Math/Singular/SOURCES/{{ version.replace('.', '-') }}/singular-{{ version }}{{ patchlevel }}.tar.gz
  sha256: 8e1f67c0a940ae772231dc5f700ab2a1b08199be26d33323558fd08d629ea91f

build:
  number: 4
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('singular', max_pin='x.x.x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('cxx') }}
    - libtool
    - automake
    - pkg-config
    - make
  host:
    - gmp
    - mpfr
    - ntl
    - libflint
    - cddlib
    - readline
    - sed
    - ncurses
  run:
    - gmp
    - mpfr
    - ntl
    - libflint
    - cddlib
    - readline
    - ncurses

test:
  commands:
    - test -f ${PREFIX}/include/singular/Singular/libsingular.h
    - test -f ${PREFIX}/lib/libSingular.a
    - test -f ${PREFIX}/lib/libSingular.dylib     # [osx]
    - test -f ${PREFIX}/lib/libSingular.so        # [linux]

about:
  home: https://www.singular.uni-kl.de/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: | 
    Singular is a computer algebra system for polynomial computations, with special emphasis
    on commutative and non-commutative algebra, algebraic geometry, and singularity theory
  dev_url: https://github.com/Singular/Sources

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
